### ISSUE TITLE
I have a problem abot the system service setting on debian 8

### ISSUE THREAD

**Issue by wyjok** [dawidd6/seedbox#4]
I have a problem when Executing the following commands.
 sudo systemctl start rtorrent
 sudo systemctl enable rtorrent
Synchronizing state for rtorrent.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d rtorrent defaults
insserv: script rtorrent is not an executable regular file, skipped!
Executing /usr/sbin/update-rc.d rtorrent enable
update-rc.d: error: cannot find a LSB script for rtorrent

**Comment by dawidd6** [comment]
Try:
`sudo chmod +x /etc/init.d/rtorrent`
or
`sudo chmod +x /etc/systemd/system/rtorrent.service`

**Comment by wyjok** [comment]
It's just because that there already is a empty rtorrent file in /etc/init.d/. I deleted it and reinstalled. Then it's worked.

**Comment by dawidd6** [comment]
Oh, right, i didn't supposed that. Glad you've figured it out. Closing
